import type { NextPage } from "next";
import Head from "next/head";
import index from "../styles/index.module.css";
//
import FirstBox from "../components/indexHome/firstBox";
import SecondBox from "../components/indexHome/secondBox";
import Footer from "../components/footer/footer";
//
const Home: NextPage = () => {
  return (
    <div className={index.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={index.main}>
        <div className={index.secondMain}>
          <FirstBox />
          <SecondBox />
        </div>
      </main>
      <Footer />
    </div>
  );
};

export default Home;
